.vscode/settings.json, README.md, mobile/README.md, mobile/package-lock.json, mobile/package.json, mobile/public/index.html, mobile/src/App.scss, mobile/src/App.tsx, mobile/src/components/CountyCandidates/CandidateCard.tsx, mobile/src/components/CountyCandidates/CountyCandidates.tsx, mobile/src/index.css
=> County Candidate Page

backend/internal/db/db.go, backend/internal/handler/statistic.go, backend/internal/routes/routes.go
please use this example to test api
curl localhost:8080/api/statistic/黃國昌?term=9
name in route param
term in query param
=> add statistic api first version

mobile/src/components/BasePaper.tsx, mobile/src/components/Candidate/AppBarChart.tsx, mobile/src/components/Candidate/Candidate.tsx, mobile/src/components/Candidate/PassPerformanceTab.tsx, mobile/src/components/Numbers/BigNum.tsx
質詢類別的長條圖
先用 @bangyuwen 給的假資料
有做展開收合，之後會整套複製到修法草案
不熟 react 跟 typescript，有寫錯再請多指教><
=> Interpellation

crawler/bulletin/__main__.py, crawler/utils/db.py
please refer to table politics in db.
=> politics info to db

backend/internal/db/db.go, backend/internal/handler/politics.go, backend/internal/models/models.go, backend/internal/routes/routes.go
try:
curl 'http://localhost:8080/api/politics/吳紹文'
=> Politics api

mobile/src/components/AppDrawer.tsx, mobile/src/components/Header/Header.scss, mobile/src/components/Header/index.tsx, mobile/src/components/Home/Home.scss, mobile/src/components/Home/index.tsx, mobile/src/index.scss
=> Home , Header new style

mobile/src/components/Candidate/AppBarChart.tsx, mobile/src/components/Candidate/AppPieChart.tsx, mobile/src/components/Candidate/CompareBarChart.tsx, mobile/src/components/Candidate/PassPerformanceTab.tsx
* 法律草案&質詢 Bar chart 串資料
* 政治獻金 pie chart 串資料
* 同選區其他候選人收支 Bar chart 串資料
=> Pass performance tab

mobile/src/App.tsx, mobile/src/components/Home/Home.scss, mobile/src/components/Home/index.tsx, mobile/src/css/_variable.scss, mobile/src/hooks/useWindowResize.ts
=> page home desktop style

mobile/src/components/Bill/ChangedBill.scss, mobile/src/components/Bill/ChangedBill.tsx
=> ChangedBill Diff line-through

mobile/public/index.html, mobile/src/components/ConstituencyCandidates/ConstituencyCandidates.tsx, mobile/src/components/ConstituencyCounty/County.tsx, mobile/src/components/ConstituencyDistrict/ConstituencyPage.scss, mobile/src/components/ConstituencyDistrict/ConstituencyPage.tsx, mobile/src/css/_loading.scss, mobile/src/index.scss
=> region style update

deploy.sh, mobile/src/App.tsx, mobile/src/components/AppDrawer.tsx, mobile/src/components/ConstituencyCandidates/CandidateCard.tsx, mobile/src/components/ConstituencyCandidates/ConstituencyCandidates.tsx, mobile/src/components/ConstituencyCounty/County.tsx, mobile/src/components/ConstituencyDistrict/ConstituencyPage.tsx, mobile/src/components/Home/index.tsx, mobile/src/components/Navigation.tsx, mobile/src/components/PartyCandidates/PartyCandidates.tsx
1. 改 router /county => /regional
2. 加入 Breadcrumb
3. CandidateCard 固定高度讓資訊不會換行
=> Add Breadcrumb

mobile/src/data/party.json
=> Regional Legislators Num

mobile/src/components/Home/Countdown.tsx, mobile/src/components/Home/Home.scss
Update Countdown animate duration
=> Update Countdown animate duration

backend/README.md
- Add `Prerequisite` section
- Add db setup steps in `Setup` section
=> docs(backend/readme.md): Add db setup steps in Setup section

mobile/src/components/ConstituencyDistrict/ConstituencyPage.tsx, mobile/src/components/IssueBill/BillDialog.tsx
1. Dialog Title Style 
https://trello.com/c/37AptFI8
2. Regional List Style
https://trello.com/c/cON3Whrs
=> Dialog Title Style & Regional List Style

mobile/src/components/CandidateCompare/CandidateCompare.scss, mobile/src/components/CandidateCompare/index.tsx
候選人比較頁
1 修正 back 回去通通導回台北市的問題
2 比較頁 + 按鈕現在會 Fixed 在 header 上
=> Condidate compare optimization

mobile/src/components/Home/index.tsx
=> Home 新增開放資料 - Facebook 廣告檔案庫

mobile/.devcontainer/Dockerfile, mobile/.devcontainer/devcontainer.json, mobile/.gitignore, mobile/README.md
add quick start guide, and hope to help anyone who wants to run the frontend website on his/her local computer easier
=> Add quick start guide by vscode + docker

mobile/package.json, mobile/src/components/Search/SearchResult.tsx, mobile/src/components/Search/SearchResultItems/SingleCandidateItemWithPartyName.tsx
1. Fix candidate type related type issue
=> 191229_Fix: fix candidate type related type issue

mobile/src/components/Candidate/Candidate.tsx, mobile/src/components/Candidate/Nav.tsx, mobile/src/components/Search/EmptySearchResult.tsx, mobile/src/components/Search/SearchResult.tsx, mobile/src/config.ts
1.  Add EmptySearchResult component to enhance search part user experience.
=> 200101_Feat: Add EmptySearchResult component

mobile/src/components/Candidate/BasicInfoTab.tsx, mobile/src/components/Candidate/Candidate.tsx
- 政見頁面改為卡片設計
https://trello.com/c/Cr9woRYl/114-%E6%94%BF%E8%A6%8B%E9%A0%81%E9%9D%A2%E6%94%B9%E7%82%BA%E5%8D%A1%E7%89%87%E8%A8%AD%E8%A8%88
=> add politics card

mobile/src/components/Candidate/StrengthTab.tsx
=> adCard電腦版兩列化

mobile/src/components/Party/index.tsx
https://trello.com/c/AR3hIUNa/163-%E6%94%BF%E9%BB%A80%E5%B8%AD-%E4%B8%8D%E9%A1%AF%E7%A4%BA%E5%B0%8F%E7%B6%A0%E9%BB%9E%E5%92%8C%E6%96%87%E5%AD%97
=> 政黨0席不顯示小綠燈

mobile/src/App.tsx, mobile/src/components/Alert.tsx, mobile/src/components/CandidateCompare/CandidateCompare.scss, mobile/src/components/CandidateCompare/CandidateCompareCardIssueBill.tsx, mobile/src/components/CandidateCompare/CandidateCompareNoInfo.tsx, mobile/src/components/ConstituencyCandidates/CompareBTN.tsx, mobile/src/components/ConstituencyCandidates/ConstituencyCandidates.scss, mobile/src/components/ConstituencyCandidates/ConstituencyCandidates.tsx, mobile/src/components/PartiesCompare/PartiesCompare.scss, mobile/src/components/PartiesCompare/PartiesCompareBills.tsx, mobile/src/components/PartiesCompare/PartiesCompareCandidates.tsx, mobile/src/components/PartiesCompare/PartiesCompareCardHeader.tsx, mobile/src/components/PartiesCompare/PartiesCompareCardHeaderFixed.tsx, mobile/src/components/PartiesCompare/PartiesComparePolitics.tsx, mobile/src/components/PartiesCompare/index.tsx, mobile/src/components/Party/index.tsx, mobile/src/components/PartyCandidates/PartyCandidates.scss, mobile/src/components/PartyCandidates/PartyCandidates.tsx, mobile/src/components/PartyCandidates/PartyCard.tsx, mobile/src/css/_color.scss, mobile/src/css/_typography.scss, mobile/src/hooks/useFetch.ts
=> Parties compares

mobile/src/components/PartiesCompare/PartiesCompareBills.tsx
1 立委提案，先換文字 即將上線
2 category 如果為空字串，就設成 "其他"
=> Fixed 立委提案, 即將上線

mobile/src/components/PartyCandidates/PartyCandidates.tsx, mobile/src/components/PartyCandidates/PartyCard.tsx
=> Fixed click Material waves area

mobile/src/components/CandidateCompare/CandidateCompare.scss, mobile/src/components/CandidateCompare/CandidateCompareCardEducation.tsx, mobile/src/components/CandidateCompare/CandidateCompareCardFB.tsx, mobile/src/components/CandidateCompare/CandidateCompareCardFBAd.tsx, mobile/src/components/CandidateCompare/CandidateCompareCardIssueBill.tsx, mobile/src/components/CandidateCompare/CandidateCompareCardPolitical.tsx, mobile/src/css/_typography.scss
=> Fixed style , 政見資料

mobile/src/components/Party/SingleCandidateItem.tsx, mobile/src/components/Search/SearchResult.tsx, mobile/src/components/Search/SearchResultItems/SingleCandidateItemWithPartyName.tsx
fix: fix Avatar src issue and title text
(修正: 不分區候選人圖片問題以及搜尋結果的"不分區立委選單名單"的標題)
=> fix: fix Avatar src issue and title text

mobile/src/components/Party/SingleCandidateItem.tsx, mobile/src/components/Search/SearchResult.tsx, mobile/src/components/Search/SearchResultItems/SingleCandidateItemWithPartyName.tsx, mobile/src/components/Search/functions/checkValuesMatched.test.tsx, mobile/src/components/Search/functions/checkValuesMatched.ts, mobile/src/components/Search/functions/filterDatasByKeyValue.ts, mobile/src/components/Search/functions/filterSearchResults.ts
fix: fix filter feature to support blur search
(現在可以模糊搜尋了)
=> Fix search part

mobile/src/components/ConstituencyCandidates/CandidateCard.tsx, mobile/src/css/_flex.scss
原住民姓名、政黨整理排版
https://trello.com/c/0nH5uthg/130-%E5%8E%9F%E4%BD%8F%E6%B0%91%E5%A7%93%E5%90%8D%E3%80%81%E6%94%BF%E9%BB%A8%E6%95%B4%E7%90%86%E6%8E%92%E7%89%88
=> CandidateCard

mobile/src/components/Candidate/BasicInfoTab.tsx
https://trello.com/c/AOa6btlD/193-padding-%E4%BF%AE%E6%AD%A3
=> padding-修正

mobile/src/components/Candidate/Candidate.tsx
fix: 非本屆立委空狀態
https://trello.com/c/7sHD1ozY/202-%E9%9D%9E%E6%9C%AC%E5%B1%86%E7%AB%8B%E5%A7%94%E7%A9%BA%E7%8B%80%E6%85%8B
=> fix: 非本屆立委空狀態

mobile/src/components/Dialog.tsx
fix: fix close Dialog with background
(修正: 卡片- 點黑色區域=關掉)
=> fix: fix close Dialog with background

mobile/src/components/AppDrawer.tsx, mobile/src/components/Candidate/Candidate.tsx, mobile/src/components/Footer/index.tsx
1. `d59479c` fixes `Drawer 新增不分區按鈕`
https://trello.com/c/cPrCtqXb
2. `fda302f` fixes `不分區候選人隱藏tab規則`
https://trello.com/c/dC46EfR4
3. `8ca5897` fixes `Footer- 拿掉'熱門議題'`
https://trello.com/c/6amAupyj
=> Candidate's tab showing rules and misc.
